<a href="https://colab.research.google.com/github/Inna-Grynishak/my_repo/blob/master/lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лабораторна робота №1
студентки КН-31 **Гринішак Інни**\
**Тема**: Google Colab, NumPy, Pandas and Matplotlib basics\
\
**Завдання:** \
1.   Ознайомлення з можливостями, налаштувати середовища Google colab. 
2.   NumPy (створити набір даних (розмір за власним рішенням), провести CRUD операції над даними (скаляр, вектор, матриця)). Властивість shape та метод  reshape. Операції над масивами. Використати arange, random.
3.   Pandas (створити dataframe різними способами, провести маніпуляції з даними (head, describe, iloc, loc, індексація з умовами відбору, групування, пошук «пустих» значень, сортування..);
4.   Matplotlib (створити набір даних лінійної функції з урахуванням помилок вимірювань, побудувати графік функції та згенерованих даних, обчислити похибку з використанням метрик MAE, MSE). Записати отримані результати у csv файл (формат: X,Y, Y_hat, mAE, mSE)
5.   Google colab різні способи завантаження наборів даних з інтернету, з власного компютера, з google-drive).
6.   Визначити параметри доступу до графічних процесорів.
7.   Відповіді оформити .ipynb документами за кожним з попередніх пунктів
8.   Викласти у зазначений репозіторій GitHub в окремій папці з назвою Lab1 де мають бути .ipynb файл та необхідні файли з даними

# Завдання 2

In [36]:
import numpy as np

# провести CRUD операції над даними (скаляр, вектор, матриця)
print('2.1 Провести CRUD операції над даними (скаляр, вектор, матриця)')
scalar = 10

array = np.array([1,2,3,4,5])

matrix = np.array([[1,0,0,0],
                   [0,1,0,0],
                   [0,0,1,0],
                   [0,0,0,1]])

print('scalar:', scalar)
print('array:\n', array)
print('matrix:\n', matrix, '\n')

scalar = 5
array[1] = 0
matrix[1][2] = 5

print('scalar:', scalar)
print('array:\n', array)
print('matrix:\n', matrix, '\n')

array = np.delete(array, [2,3])
matrix = np.delete(matrix, 1, 0)

print('array:\n', array)
print('matrix:\n', matrix, '\n\n')

# Властивість shape та метод reshape
print('2.2 Властивість shape та метод reshape')
array = np.array([1,2,3,4,5,6])

print('array SHAPE:\n', array.shape)
array = np.reshape(array, (3,2))
print('array:\n', array)
print('array reSHAPE:\n', array.shape, '\n')

print('matrix SHAPE:\n', matrix.shape)
matrix = np.reshape(matrix, 12)
print('matrix:\n', matrix)
print('matrix reSHAPE:\n', matrix.shape, '\n\n')

# Операції над масивами
print('2.3 Операції над масивами')
array = np.array([1,2,3])
matrix = np.array([[1,2,3],
                   [2,3,1],
                   [3,1,2]])

print('* 10\n', matrix*10, '\n')
print('+ 10\n', matrix+10, '\n')
print('- 10\n', matrix-10, '\n')
print('/ 10\n', matrix/10, '\n')
print('Matrix * Matrix\n', np.dot(array, matrix), '\n\n')

# Використати arange, random
print('2.4 Використати arange, random')
array = np.arange(3)
print('array:\n', array)

array = np.arange(1, 5)
print('array:\n', array)

array = np.arange(1, 5, 0.75)
print('array:\n', array)

array = np.random.randn(5)
print('array:\n', array)

2.1 Провести CRUD операції над даними (скаляр, вектор, матриця)
scalar: 10
array:
 [1 2 3 4 5]
matrix:
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]

scalar: 5
array:
 [1 0 3 4 5]
matrix:
 [[1 0 0 0]
 [0 1 5 0]
 [0 0 1 0]
 [0 0 0 1]]

array:
 [1 0 5]
matrix:
 [[1 0 0 0]
 [0 0 1 0]
 [0 0 0 1]]


2.2 Властивість shape та метод reshape
array SHAPE:
 (6,)
array:
 [[1 2]
 [3 4]
 [5 6]]
array reSHAPE:
 (3, 2)

matrix SHAPE:
 (3, 4)
matrix:
 [1 0 0 0 0 0 1 0 0 0 0 1]
matrix reSHAPE:
 (12,)


2.3 Операції над масивами
* 10
 [[10 20 30]
 [20 30 10]
 [30 10 20]]

+ 10
 [[11 12 13]
 [12 13 11]
 [13 11 12]]

- 10
 [[-9 -8 -7]
 [-8 -7 -9]
 [-7 -9 -8]]

/ 10
 [[0.1 0.2 0.3]
 [0.2 0.3 0.1]
 [0.3 0.1 0.2]]

Matrix * Matrix
 [14 11 11]


2.4 Використати arange, random
array:
 [0 1 2]
array:
 [1 2 3 4]
array:
 [1.   1.75 2.5  3.25 4.   4.75]
array:
 [ 1.82442479 -0.18775001 -1.65417461  0.15998509 -0.47828384]

# Завдання 3

In [63]:
import numpy as np
import pandas as pd

# створити dataframe різними способами
print('3.1 Cтворити dataframe різними способами\n')
df = pd.DataFrame({'name': ['Inna', 'Oleg', 'Ira', 'Liza'], 'role': ['student', 'student', 'student', 'student'],  'age': [19, 19, 20, 21] })
display(df)

df1 = pd.DataFrame([['Inna', 'student', 19], ['Oleg', 'student', 19], ['Ira', 'student', 20], ['Liza', 'student', 21]], columns=['name', 'role', 'age'], index=['row1','row2','row3','row4'])
display(df1)

df2 = pd.Series([0,2,4,6])
df2 = pd.DataFrame({'#':df2})
display(df2)

# провести маніпуляції з даними (head, describe, iloc, loc, індексація з умовами відбору, групування, пошук «пустих» значень, сортування..)
print('\n3.2 Провести маніпуляції з даними (head, describe, iloc, loc, індексація з умовами відбору, групування, пошук «пустих» значень, сортування..)\n')

display("head(2)", df.head(2))
print('\n')
display("describe", df['name'].describe())
print('\n')
display("iloc", df.iloc[3])
print('\n')
display("loc", df1.loc['row2'])

# індексація з умовами відбору

display(pd.Da)
print('\nсортування')
df.sort_values(by=['name'], ascending=True)

3.1 Cтворити dataframe різними способами

   name     role  age
0  Inna  student   19
1  Oleg  student   19
2   Ira  student   20
3  Liza  student   21

      name     role  age
row1  Inna  student   19
row2  Oleg  student   19
row3   Ira  student   20
row4  Liza  student   21

   #
0  0
1  2
2  4
3  6

3.2 Провести маніпуляції з даними (head, describe, iloc, loc, індексація з умовами відбору, групування, пошук «пустих» значень, сортування..)

'head(2)'

   name     role  age
0  Inna  student   19
1  Oleg  student   19

'describe'

count        4
unique       4
top       Inna
freq         1
Name: name, dtype: object

'iloc'

name       Liza
role    student
age          21
Name: 3, dtype: object

'loc'

name       Oleg
role    student
age          19
Name: row2, dtype: object

сортування

   name     role  age
0  Inna  student   19
2   Ira  student   20
3  Liza  student   21
1  Oleg  student   19